### ISSUE TITLE
von-network with Raspberry Pi 4

### ISSUE THREAD

**Issue by srbms23** [bcgov/von-network#140] opened 2021-03-30 14:24 UTC
Hi, 

I wanted to use aca-py Cloud Agent on RP4 together with von-network? 

Is there a way to run von-network on Pi because I think, because of different architectures it won´t be possible with docker?

Alternatively, is there a way to run von-network on my PC and connect it with Agent on Pi?

Thanks in advance!

**Comment by srbms23** [comment] 2021-04-06 09:34
Hi @WadeBarnes, thanks a lot for your help! :)
However, I have another question.
After I expose von-network on my mac IP address, I want to connect it with Aries Cloud Agent that is on RP4. 
So are all nodes automatically exposed on mac IP address with the same ports as in Genesis file (for example, in my case the port for Node1 is 9701) or there is still something else I need to do so I can connect my Aries Cloud Agent with von-network?

**Comment by WadeBarnes** [comment] 2021-04-07 13:28
You need to register your agent in the ledger, and connect it to the network via the genesis file.

Once you have the ledger running you can register you're agent's DID via the UI:
![image](https://user-images.githubusercontent.com/10504350/113874071-43843f00-976a-11eb-8451-9bf32900cf2f.png)

Then you'll be able to use the genesis file to connect your agent to the ledger.  Use the genesis url for your ledger, example; http://dev.bcovrin.vonx.io/genesis

**Comment by srbms23** [comment] 2021-04-09 07:17
I did everything as you said and error is still the same. 


Could you @WadeBarnes make sure that all steps that I´ve done during installation on Pi are ok:

1) Installed Libindy as in: https://wiki.hyperledger.org/display/INTERN/Collaboration%3A+Raspberry+Pi+Indy+Agent#Collaboration:RaspberryPiIndyAgent-AgentFrameworkforARMv7

Indy-sdk: master-branch.


2) Installed Aries Cloud Agent from master branch.

I used commands:
```
git clone https://github.com/hyperledger/aries-cloudagent-python.git
cd aries-cloudagent-python
pip install wheel 
pip install -e .
```

After that I got an error that indy is not available so I installed it also using pip and the error is gone.

I started von-network on my macbook using `./manage start 192.168.2.1` because that is ip address of my macbook and each Node now has Ip of my macbook and Ports are 9701, 9703, 9705, 9707.
Then I followed the steps from your second comment above and registered DID with seed.

To start Agent on RPi I can only use aca-py commands without wallet like for example:

`aca-py start --label Alice --inbound-transport http 0.0.0.0 8020 --outbound-transport http --admin 0.0.0.0 11000 --admin-insecure-mode --genesis-url http://192.168.2.1:9000/genesis --seed Alice000000000000000000000000001 --endpoint http://192.168.2.9:8020 --debug-connections --auto-provision `

And my Agents is listening... However, when I try to send Schema to the ledger I get error from my second comment:
"403 No ledger available".

If I add `--wallet-type indy --wallet-name Alice1 --wallet-key secret` as commands I get another error:
`open_wallet() got an unexpected keyword argument 'config'`, as in picture below.
In this case, Agent doesn´t even start.

Could you or someone tell me what version of aries cloud agend and indy works best on RPi? Did I miss something during installation? On my macbook everything works perfectly but on Pi... 
Is there a way to solve my problems above, what else could I do?


Thanks a lot for your time! 
![image](https://user-images.githubusercontent.com/81626585/114140386-78ca9180-9910-11eb-8395-57ae45b2de85.png)

**Comment by WadeBarnes** [comment] 2021-04-09 15:50
Are your macbook and the Pi on the same network?  Please confirm the IP addresses of the macbook and the pi.

**Comment by swcurran** [comment] 2021-04-09 15:52
Wade -- would it be easier to use a public BCovrin ledger for this?

**Comment by WadeBarnes** [comment] 2021-04-09 15:54
Could be.  Link to `dev` already provided above.

**Comment by srbms23** [comment] 2021-04-09 16:12
Hi @WadeBarnes,

I am sharing WiFi from my MacBook to Pi, so macbook is a WiFi hotspot. Do you think that might be a problem? I can also try with regular WiFi connection tomorrow.

**IPs:** 
macbook: 192.168.2.1
Pi: 192.168.2.9

I will also try with public ledger as second option. 

Could you or @swcurran maybe help me with second problem from the picture above, `open_wallet() got an unexpected keyword argument 'config'` ?

Thanks a lot!

**Comment by WadeBarnes** [comment] 2021-04-09 16:23
Try the public ledger.  Also, have you you tried getting this all up and running on your MacBook first?  That way you will have a known stating point for when your working on the Pi, and if you run into issues it will be easier to debug.  Currently, with debugging on the Pi, there are too many variables involved.

Get it working on your mac.  Replicate the setup and config on the pi (using the Pi specific builds/configurations and needed).  If you run into issues at that point we know it's Pi specific and likely due to dependency issues.

**Comment by srbms23** [comment] 2021-04-15 11:56
Hi @WadeBarnes ,
I tried to install everything on mac and I have the same problem in both cases with `von-network` as well as public ledger. Do you think that endpoint could be a problem? Is it ok when I say `--endpoint http://localhost:8020` when I want to run aca-py on my mac locally?

I can run Agent with docker on mac using for example http://dev.greenlight.bcovrin.vonx.io/ and I had to slightly change the commands to:

`PORTS="8020 11000" ./scripts/run_docker start --label Alice --genesis-url http://dev.greenlight.bcovrin.vonx.io/genesis --inbound-transport http 0.0.0.0 8020 --outbound-transport http --admin-insecure-mode --endpoint http://192.168.56.133:8020 --admin 0.0.0.0 8021 --seed Alice000000000000000000000000001 --debug-connections --auto-provision --wallet-type indy --wallet-name Alice --wallet-key secret
`

Another possible problem that I see is python version. Does aca-py support higher Python versions? Docker image uses I think 3.6 and I have later versions on my mac and Pi. I can downgrade to 3.6 but not sure if that changes something.

Thanks a lot!

**Comment by esune** [comment] 2021-04-15 16:15
> 
@srbms23 the agent endpoint needs to be addressable by other agents that are not running on the same machine, so 
using `localhost` is definitely going to cause issues. Using `--endpoint http://192.168.56.133:8020` (or whatever explicit IP address is required) seems like the right way to go for that part.

I am trying to reproduce the other error locally to see how if I can get a better understanding of what the issue could be.

**Comment by esune** [comment] 2021-04-15 16:49
@srbms23 I think you have your dependencies wrong, in particular when you hit the issue with indy you probably run `pip install indy` which is not the right dependency - you need `pip install python3-indy` instead. I Did a step-by-step recreation of the issue on Ubuntu 20.04 and funny enough I hit the same problem. I am using python 3.8.

After installing the right package, I was able to start my agent by using this command (it should be the same if you're running a `von-network`, I used a hosted ledger to reduce the setup steps):
```
aca-py start --label Alice --inbound-transport http 0.0.0.0 8020 --outbound-transport http --admin 0.0.0.0 11000 --admin-insecure-mode --genesis-url  http://dev.greenlight.bcovrin.vonx.io/genesis --seed Alice000000000000000000000000001 --endpoint http://192.168.1.172:8020 --debug-connections --auto-provision
```
Please note that the agent endpoint is explicitly set to the IP address of the machine it is running on.

I am not 100% familiar with what `pip install -e .` does, but I *think* for your purpose you could/should instead run:
```
pip install -r requirements.txt
pip install -r requirements.dev.txt
pip install -r requirements.indy.txt
```

OR, which may be even easier if you just want to run the agent on your Raspberry Pi:
```
pip install aries-cloudagent
```
which will install the latest tagged release.

Either way, this does not seem to be an issue with `von-network` or `aries-cloudagent`. Please let me know if you need further clarifications.

**Comment by srbms23** [comment] 2021-04-16 11:23
Hi @esune ,
thanks for your answer! 

I am still really confused when it comes to IP address for endpoint and I am not able to start Agent on Pi. Could you take a look one more time if everything that I have done is ok?


I tried with `192.168.2.9` and that is the same IP address that I use to connect remotely PC with Pi and that is the one that I used for endpoint. Whole command line is:

`aca-py start --label Alice --inbound-transport http 0.0.0.0 8020 --outbound-transport http --admin 0.0.0.0 11000 --admin-insecure-mode --genesis-url http://dev.greenlight.bcovrin.vonx.io/genesis --seed Alice000000000000000000000000001 --endpoint http://192.168.2.9:8020 --debug-connections --auto-provision `

And Error looks like this:

![image](https://user-images.githubusercontent.com/81626585/115016858-f1ec5a80-9eb5-11eb-86dd-29451e2317f1.png)


If I add `--wallet-type indy --wallet-name Alice1 --wallet-key secret` I am not able to start Agent and Error looks like this:

![image](https://user-images.githubusercontent.com/81626585/115016977-1fd19f00-9eb6-11eb-975e-ca53ea8853ae.png)


I think first Issue is related to the IP for endpoint that I need. When I use docker on my mac laptop I get explicite IP for container and it works with that one. If I type wrong IP I get the same Error.

Just to make sure that I did everything right. So you propose to uninstall indy-sdk and install python3-indy? That´s what I did.

Thanks a lot and I really appreciate your time and help!

**Comment by esune** [comment] 2021-04-19 23:59
So, the first error you are posting appears when you try to post a schema definition, not on startup - correct?
Are you sure you are using the latest version of the aca-py code? If not, which version are you using? The line that is throwing the error (line `156`) does not match the current code on aca-py `main` so maybe your code is outdated?
The error seems related to having the wrong endpoint for the ledger: I do not know how your network and Pi are set-up, but the Pi needs to be able to reach the IP where the ledger is hosted. The `--endpoint` only defines what URL is used by the agent to be addressable by other agents.

I unfortunately do not have a real suggestion about the segmentation fault, wondering if it could be due to the limited resources on the Pi maybe?

I think you'll be better off asking this in either the `aries-cloudagent-python` repository and/or in the Rocket.Chat channel with the same name: I might be the one answering there as well, but you will also get a bigger audience with more/varied experience with aca-py - this doesn't look like it is `von-network` related at this point.

**Comment by srbms23** [comment] 2021-04-20 07:37
Hi @esune ,

I am using `aca-py 0.6.0`, cloned from github and requirements installed, but as you said I am not sure why it doesn´t match with current `main`.
Maybe I will try to reinstall everything and do step by step one more time.

Right now I am more interested in `403 Error: No ledger available` and what is wrong there. I get the same error on my mac so it has to be configuration. I want to try to make it work on Pi since it would be really usefull for testing stuff. :) 

I will try to get an answer in Rocket.Chat.

**Comment by esune** [comment] 2021-04-20 16:07
I'll switch to Rocket.Chat as well and close this issue then!

**Closed by esune** 2021-04-20 16:07 UTC
