### ISSUE TITLE
von-network not building

### ISSUE THREAD

**Issue by swcurran** [bcgov/von-network#262] opened 2023-05-31 02:04 UTC
All [Aries Agent Test Harness](https://github.com/hyperledger/aries-agent-test-harness) tests failed yesterday because the local Indy ledger did not start up for all.  Traced the issue to von-network not building.

Running this: `./manage rebuild`

Triggered this error:

```
#8 12.38 Installing collected packages: pip
#8 12.38   Attempting uninstall: pip
#8 12.38     Found existing installation: pip 21.3.1
#8 12.64     Uninstalling pip-21.3.1:
#8 12.65       Successfully uninstalled pip-21.3.1
#8 13.37 ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
#8 13.37 indy-plenum 1.13.0.dev0 requires base58==1.0.0, but you have base58 1.0.3 which is incompatible.
#8 13.37 indy-plenum 1.13.0.dev0 requires python-rocksdb==0.6.9, but you have python-rocksdb 0.7.0 which is incompatible.
#8 13.37 indy-plenum 1.13.0.dev0 requires rlp==0.5.1, but you have rlp 0.6.0 which is incompatible.
#8 13.37 indy-node 1.12.6 requires indy-plenum==1.12.6, but you have indy-plenum 1.13.0.dev0 which is incompatible.
#8 13.37 Successfully installed pip-9.0.3
```

Not sure what has changed, but clearly something has.

**Comment by swcurran** [comment] 2023-05-31 02:04
@WadeBarnes -- can you please take a look?  Thanks!

**Comment by swcurran** [comment] 2023-05-31 02:08
AATH would have last successfully run 2 days ago. That said, I can’t see any of the PRs that have been merged in von-network as the likely culprit.

**Comment by WadeBarnes** [comment] 2023-05-31 14:06
Those errors don't cause the build to fail.  They are actually false reports, and are caused by the reinstall of pip-9.0.3 at the von-network Dockerfile level.  All of those packages at those versions are already contained in the `bcgovimages/von-image:node-1.12-6` base image.  This is a side effect of this code that was added during the migration to indy-vdr:
https://github.com/bcgov/von-network/blob/ffc62d53f89c945509606b0352d6bf357f7d82f1/Dockerfile#L9-L14

**Comment by swcurran** [comment] 2023-05-31 14:07
I know that all AATH runs failed because the local ledger did not start, so something is not working.

**Comment by WadeBarnes** [comment] 2023-05-31 14:18
NM - Found some logs.  von-network is building, it's just not starting.  I made a couple changes yesterday to fix some issues I had during the BCovrin Test upgrade.  I'll start by looking at those.

**Comment by WadeBarnes** [comment] 2023-05-31 19:48
The startup issue has been fixed with https://github.com/bcgov/von-network/pull/263

**Closed by WadeBarnes** 2023-05-31 19:48 UTC
